
// 200 Adjectives (all 7 characters or fewer)
export const Adjectives = [
  "Able", "Active", "Agile", "Angry", "Anxious", "Apt", "Artful", "Awesome",
  "Basic", "Best", "Big", "Bitter", "Blithe", "Bold", "Bossy", "Brave",
  "Bright", "Brisk", "Bubbly", "Busy", "Calm", "Capable", "Cheery", "Chill",
  "Clean", "Clear", "Clever", "Cool", "Crazy", "Crisp", "Cute", "Dainty",
  "Daring", "Dear", "Deep", "Dizzy", "Dope", "Dull", "Eager", "Early", "Easy",
  "Epic", "Even", "Exact", "Fair", "Famous", "Fancy", "Fast", "Feisty",
  "Fine", "Firm", "First", "Fit", "Flaky", "Flashy", "Flat", "Fluffy",
  "Foolish", "Free", "Fresh", "Fun", "Funny", "Fuzzy", "Giant",
  "Gifted", "Glad", "Gleeful", "Good", "Grand", "Great", "Green", "Grim",
  "Gross", "Grumpy", "Happy", "Hard", "Harsh", "Hasty", "Healthy", "Helpful",
  "High", "Honest", "Hot", "Humble", "Icy", "Ideal", "Idle", "Inert",
  "Jazzy", "Jolly", "Joyful", "Juicy", "Kind", "Large", "Lazy",
  "Light", "Lively", "Local", "Loud", "Lovely", "Lucky", "Mad", "Major",
  "Meek", "Merry", "Mild", "Mini", "Moody", "Muddy", "Narrow", "Nasty",
  "Neat", "Nervous", "New", "Nice", "Nifty", "Noisy", "Normal", "Odd",
  "Old", "Open", "Pale", "Peachy", "Perfect", "Plain", "Plucky", "Polite",
  "Poor", "Posh", "Proud", "Quick", "Quiet", "Rapid", "Rare", "Real",
  "Rich", "Rigid", "Rough", "Rude", "Safe", "Salty", "Same", "Savvy",
  "Sharp", "Short", "Shy", "Silly", "Simple", "Slim", "Slow", "Small",
  "Smart", "Smug", "Soft", "Solid", "Sore", "Sour", "Spicy", "Spunky",
  "Steady", "Strong", "Stuck", "Sunny", "Super", "Sweet", "Swift", "Tall",
  "Tame", "Tasty", "Tender", "Thin", "Thirsty", "Tidy", "Tight", "Tiny",
  "Tired", "Tough", "Trendy", "True", "Ugly", "Upbeat", "Useful", "Vague",
  "Vast", "Vivid", "Warm", "Weak", "Weird", "Wet", "Wide", "Wild", "Witty",
  "Wizzy", "Woolly", "Worried", "Wry", "Young", "Yummy", "Zany", "Zesty"
];
// 200 nouns (all 6 characters or fewer)
export const Nouns = [
  "Actor", "Agent", "Alien", "Ant", "Apple", "Arrow", "Artist", "Ash", "Axe", "Badge",
  "Bag", "Ball", "Band", "Barn", "Base", "Bat", "Bear", "Bee", "Bell", "Berry",
  "Bike", "Bird", "Blade", "Boat", "Bomb", "Bone", "Book", "Boot", "Boss", "Bow",
  "Box", "Boy", "Brain", "Brick", "Bridge", "Brush", "Bubble", "Bunny", "Bus", "Bush",
  "Cake", "Camp", "Can", "Candle", "Cannon", "Cape", "Car", "Card", "Cart", "Cat",
  "Chair", "Chart", "Chef", "Chest", "Chip", "Circle", "City", "Claw", "Cloud",
  "Clown", "Coach", "Coat", "Code", "Coin", "Comet", "Cook", "Coral", "Corn", "Cow",
  "Crab", "Craft", "Crate", "Crew", "Crown", "Cube", "Cup", "Dance", "Dart", "Deer",
  "Desk", "Dish", "Dog", "Doll", "Door", "Dot", "Dragon", "Drill", "Drum", "Duck",
  "Eagle", "Edge", "Egg", "Elf", "Engine", "Eye", "Face", "Fan", "Farm",
  "Fence", "Field", "Film", "Fire", "Fish", "Flag", "Flame", "Flash", "Flock", "Flower",
  "Fly", "Food", "Foot", "Force", "Fork", "Fox", "Frog", "Fruit", "Game", "Gap",
  "Garden", "Gate", "Gem", "Ghost", "Gift", "Girl", "Glass", "Glove", "Goat", "Gold",
  "Golf", "Goose", "Grape", "Grass", "Grid", "Group", "Guard", "Guitar", "Gun", "Hammer",
  "Hand", "Hat", "Hawk", "Head", "Heart", "Hill", "Hog", "Hook", "Horn", "Horse",
  "House", "Ice", "Idea", "Ink", "Island", "Jelly", "Jet", "Jewel", "Job", "Jungle",
  "Key", "Kid", "King", "Kite", "Knife", "Koala", "Ladder", "Lake", "Lamp", "Leaf",
  "Leg", "Lemon", "Lion", "Lizard", "Lock", "Log", "Loom", "Loop", "Map", "Mask",
  "Match", "Maze", "Meadow", "Milk", "Mine", "Monkey", "Moon", "Moss", "Mouse", "Mud",
  "Mug", "Mule", "Nail", "Nest", "Net", "Note", "Oak", "Ocean", "Oven", "Owl", "Panda",
  "Paper", "Park", "Parrot", "Peach", "Pearl", "Pen", "Pencil", "Pet", "Phone", "Pig",
  "Pine", "Pizza", "Plane", "Plant", "Plate", "Plug", "Plum", "Poem", "Pond", "Pop",
  "Poppy", "Pouch", "Prize", "Pump", "Puppy", "Puzzle"
];